# -*- coding: utf-8 -*-
"""Input_Pipeline_Creation_DR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JNOHw2ATQ88L1II4R72phK_Ahx0ZhCk4
"""

''' Creation of an input pipeline for the IDRID dataset
Changes to be made according to your requirements is mentioned with '**TO_BE_CHANGED**' macro.
Please adapt it accordingly.
Folder structure of the dataset
    ROOT_FOLDER(/home/user/.../IDRID_dataset)
       |-------- images
       |            |------ train
       |            |           |------ IDRiD_001.jpg
       |            |                   etc...
       |            |------ test
       |                        |------ IDRiD_001.jpg
       |                                etc...
       |
       | -------- labels                 
       |             |
       |             | ----- test.csv
       |             | ----- train.csv
       |
    ```
'''

#import necessary packages
import tensorflow as tf
import pandas as pd
import numpy as np
import zipfile
import glob, os
import matplotlib.pyplot as plt
from PIL import Image
print(tf.__version__)

# Constants

BATCH_SIZE = 32
BASE_PATH = '/content/drive/MyDrive/IDRID_dataset'
img_height = 256
img_width = 256

#TO_BE_CHANGED
#Mounting the contents to Google Drive
from google.colab import drive
drive.mount('/content/drive')

#Unzip the dataset to a path in the drive
!unzip -uq "/content/drive/My Drive/idrid.zip" -d "/content/drive/My Drive/"
print('Unzipped the contents to the drive')

#TO_BE_CHANGED
#Load the images for training
train_images = glob.glob("/content/drive/MyDrive/IDRID_dataset/images/train/*.jpg")
print("Loaded training images")
#Read the CSV file containing the labels and images for training
#We have labels from 0 to 4 here
df_load_train_csv = pd.read_csv(BASE_PATH + '/labels/train.csv')
train_labels = (df_load_train_csv['Retinopathy grade'].values).tolist()

#Debug
#print(train_images,type(train_images),len(train_images))
#print(train_labels,type(train_labels),len(train_labels))

#TO_BE_CHANGED
#Load the test images
test_images = glob.glob("/content/drive/MyDrive/IDRID_dataset/images/test/*.jpg")
print("Loaded images for testing")
#Read the CSV file containing the labels and images for test

df_load_test_csv = pd.read_csv('/content/drive/MyDrive/IDRID_dataset/labels/test.csv')
test_labels = (df_load_test_csv['Retinopathy grade'].values).tolist()

#Debug
#print(test_images,type(test_images),len(test_images))
#print(test_labels,type(test_labels),len(test_labels))

